### PR TITLE
Set DJANGO_SETTINGS_MODULE before the tests

### PR DESCRIPTION
**Pull request by joshmoore**
Tested with:

```
git clone -b django_tests git://github.com/will-moore/figure omero-figure # name is important!
cd omero-figure
git clone git://github.com/openmicroscopy/omero-test-infra .omero # name is important!
.omero/docker app
```

I still had a few regular failures, but those are assertions for @will-moore to look at.

### CODE REVIEW

**Comment by will-moore** [comment]
I get....
```
==================================== ERRORS ====================================
___________ ERROR collecting test/integration/test_figure_scripts.py ___________
import file mismatch:
imported module 'test_figure_scripts' has this __file__ attribute:
  /Users/wmoore/Desktop/FIGURE/figure/test/integration/test_figure_scripts.py
which is not the same as the test file we want to collect:
  /omero-figure/test/integration/test_figure_scripts.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.20 seconds ============================
```
Tried ```$ rm -rf __pycache__/``` but got same error...

**Comment by will-moore** [comment]
That was after adding a new-line at end of file ```test/integration/test_figure_files.py``` which was the original flake8 error.

**Comment by joshmoore** [comment]
Are you running in docker or locally? If the latter, then try: `find . -name __pycache__`

**Comment by will-moore** [comment]
I'm running ```$ .omero/docker app``` locally.

```
$ find . -name __pycache__
./test/integration/__pycache__
$ rm -rf ./test/integration/__pycache__
$ .omero/docker app
...
========================== 5 failed in 13.34 seconds ===========================
```
So the tests are running now, Thanks.
But it takes a few minutes to run each time, so debugging might take a while.

**Comment by will-moore** [comment]
The scripts tests are failing because the scripts aren't found
```
        id = super(TestFigureScripts, self).get_script_by_name(path, name)
>       assert id > 0
E       assert -1 > 0
```
But even if I use
```
$ .omero/docker app scripts
```
it still fails, possibly because I need @jburel's branch of ```omero-test-infra```?

**Comment by jburel** [comment]
the branch has been merged

**Comment by will-moore** [comment]
My test is failing with
```
        rsp = get(django_client, request_url, data, status_code, csrf)
>       assert rsp.get('Content-Type') == 'application/json'
E       AssertionError

/opt/omero/web/OMERO.web/lib/python/omeroweb/testlib/__init__.py:362: AssertionError
```
Normally to debug that, I would go into ```omeroweb/testlib/__init__.py``` and add
```
print rsp
```
right before the assertion so I can see the error message.
But I guess that's not an option in this setup?

**Pull request merged**
